<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="2" hostname="DESKTOP-6ST94J7" failures="1" tests="2" name="Test-1" time="0.014" errors="0" timestamp="2021-06-03T14:14:58 EDT">
  <testcase classname="com.testNGListenerDemo.GroupDemo2" name="test4" time="0.001">
    <failure type="java.lang.AssertionError" message="expected [3] but found [2]">
      <![CDATA[java.lang.AssertionError: expected [3] but found [2]
at com.testNGListenerDemo.GroupDemo2.test4(GroupDemo2.java:26)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- test4 -->
  <testcase classname="com.testNGListenerDemo.GroupDemo2" name="test2" time="0.0">
    <skipped/>
  </testcase> <!-- test2 -->
  <testcase classname="com.testNGListenerDemo.GroupDemo2" name="test1" time="0.0">
    <ignored/>
  </testcase> <!-- test1 -->
  <testcase classname="com.testNGListenerDemo.GroupDemo2" name="test3" time="0.0">
    <ignored/>
  </testcase> <!-- test3 -->
</testsuite> <!-- Test-1 -->
